### ISSUE TITLE
Initialization of moving average of entropy

### ISSUE THREAD

**Issue by e0jun** [mr-eggplant/SAR#4]
Hello author,
Thanks for the release of the code of your paper. 

The (pseudo) code shows that the moving average value of entropy loss is not initialized to 0 after the model recovery.

I think the value should be initialized to 0. Could you give me an answer?

Thank you in advance:-)

**Comment by mr-eggplant** [comment]
Hi e0jun,

The e_0 should be re-initialized after each time recovery (as we did in _sar.py_). We missed this in the pseudo-code. Thank u for pointing this out!

Best,

**Comment by e0jun** [comment]
Thank you for your quick reply!

In sar.py, the _ema_ value is returned with _reset_flag_ in line 49.
If _reset_flag_ is True, the _self.ema_ is re-initialized in line 51. 
But, in line 52, the returned _ema_ is re-allocated to _self.ema_, making the re-initialization negligible. 

It could be my misunderstanding, but could you explain the re-initialization process? If you give me an answer, I really appreciate it!!

**Comment by mr-eggplant** [comment]
Hi,

To make the re-initialization of $e_m$ effective, line 52 should actually be placed before line 50. 

However, I think that the performance would not be clearly affected whether we reset $e_m$ or not. This is because, once the model is reset, the entropy of the new predictions $e$ will be much higher than $e_m$ , causing $e_m$ to quickly become large after a few iteration steps of _ema_ update.

Hope that helps

**Comment by e0jun** [comment]
I understand! I really appreciate your reply:)
