### ISSUE TITLE
About attaching SAR to segmentation model (cotta) 

### ISSUE THREAD

**Issue by daeunni** [mr-eggplant/SAR#7]
Hi, 
thanks for your nice work :) 
how can I attach this SAR method to the segmentation models? (like presented in Cotta)

**Comment by mr-eggplant** [comment]
Hi Daeun,

Thanks for your interest! And apologies for the delayed response. The graduation season is quite busy.

The most straightforward way to apply SAR to segmentation models is by minimizing the reliable entropy and sharpness at the pixel level (classification). However, I do not sure about its performance since I haven’t tested this :)

In our previous studies, we applied EATA (our another selective entropy-based method) to segmentation tasks (BDD-100K, Cityscapes, Mapillary datasets) and found that it works.

So, feel free to try SAR on your own segmentation tasks. But you may need to tune the hyper-parameters correspondingly.

Kindly let me know if you have further results and findings and Welcome further discussions :)

Best regards,

Shuaicheng

**Comment by daeunni** [comment]
Thanks for your reply :) 
I also checked your paper EATA, but could you provide the code of EATA for the segmentation version? :0

**Comment by mr-eggplant** [comment]
Hi, could you provide your email address, or, reach out to me at niushuaicheng@gmail.com?  I will share the code via email.

**Comment by daeunni** [comment]
Thanks a lot! My email address is goodgpt@korea.ac.kr :)

**Comment by mr-eggplant** [comment]
done :)
